"""adding job_title field to time entry model

Revision ID: 1e0bd381894e
Revises: 35edc0e33ee5
Create Date: 2025-12-15 17:44:54.358790+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e0bd381894e'
down_revision: Union[str, Sequence[str], None] = '35edc0e33ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping projects table and index as they don't exist in SQLite
    # Skip altering end_utc column as SQLite doesn't support ALTER COLUMN
    op.add_column('time_entries', sa.Column('job_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip altering end_utc column as SQLite doesn't support ALTER COLUMN
    op.drop_column('time_entries', 'job_title')
    # Skip recreating projects table and index as they don't exist in SQLite
    # ### end Alembic commands ###
