"""add auth fields to users

Revision ID: 35edc0e33ee5
Revises: 5ea3e1f09b1e
Create Date: 2025-09-15 15:34:52.065170+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35edc0e33ee5'
down_revision: Union[str, Sequence[str], None] = '5ea3e1f09b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
