"""update models

Revision ID: 5ea3e1f09b1e
Revises: 149f73c2f800
Create Date: 2025-09-10 21:31:49.380521+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea3e1f09b1e'
down_revision: Union[str, Sequence[str], None] = '149f73c2f800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('token_version', sa.String(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('last_password_change', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_password_change')
    op.drop_column('users', 'token_version')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
