"""add org tables and user org fields

Revision ID: 71d4d76f6162
Revises: 9c291c8972e9
Create Date: 2026-05-11 15:18:41.411743+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d4d76f6162'
down_revision: Union[str, Sequence[str], None] = '9c291c8972e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_invite_code'), 'organizations', ['invite_code'], unique=True)
    op.add_column('users', sa.Column('org_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_org_admin', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('account_type', sa.String(), server_default='solo', nullable=False))
    # Foreign key constraint handled at the SQLAlchemy model level (ForeignKey in Column)
    # SQLite does not support adding FK constraints via ALTER TABLE
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Foreign key constraint is handled at the model level, no need to drop
    op.drop_column('users', 'account_type')
    op.drop_column('users', 'is_org_admin')
    op.drop_column('users', 'org_id')
    op.drop_index(op.f('ix_organizations_invite_code'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
