"""init schema

Revision ID: ab77590992df
Revises: 
Create Date: 2025-09-03 13:43:59.067842+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab77590992df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_code', sa.String(), nullable=False),
    sa.Column('activity', sa.String(), nullable=False),
    sa.Column('start_utc', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_utc', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_time_entries_user_start', 'time_entries', ['user_id', 'start_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_time_entries_user_start', table_name='time_entries')
    op.drop_table('time_entries')
    # ### end Alembic commands ###
